server:
  port: 8080

spring:
  redis:
    database: 0
    host: 101.132.105.38
    port: 6379
    password: 1899
    #      jedis:
    #        pool:
    #          max-active: 8
    #          max-wait: -1
    #          max-idle: 8
    #          min-idle: 0
    timeout: 500